export const gateways = [
  {
    name: 'Admin Console',
    kind: 'Firebase Hosting',
    environment: 'Production',
    url: 'https://prevleak-admin.web.app',
    port: '443',
    status: 'Operational',
    icon: 'ShieldCheck',
  },
  {
    name: 'Group Website',
    kind: 'Firebase Hosting',
    environment: 'Production',
    url: 'https://prevleak-landing.web.app',
    port: '443',
    status: 'Operational',
    icon: 'Globe2',
  },
  {
    name: 'Multi-container App',
    kind: 'Docker Compose',
    environment: 'Local',
    url: 'http://localhost:3000',
    port: '3000',
    status: 'Operational',
    icon: 'PanelsTopLeft',
  },
  {
    name: 'Bind-mount App',
    kind: 'Docker Compose',
    environment: 'Local',
    url: 'http://localhost:3001',
    port: '3001',
    status: 'Operational',
    icon: 'Container',
  },
  {
    name: 'Docker Registry',
    kind: 'Registry API v2',
    environment: 'Local',
    url: 'http://localhost:5000/v2/',
    port: '5000',
    status: 'Operational',
    icon: 'PackageOpen',
  },
  {
    name: 'Todo Database',
    kind: 'MongoDB 6',
    environment: 'Local',
    url: 'mongodb://localhost:27017',
    port: '27017',
    status: 'Operational',
    icon: 'Database',
  },
  {
    name: 'Bind-mount Database',
    kind: 'MongoDB 6',
    environment: 'Local',
    url: 'mongodb://localhost:27018',
    port: '27018',
    status: 'Operational',
    icon: 'Database',
  },
  {
    name: 'GitHub Copilot MCP',
    kind: 'Remote MCP / OAuth',
    environment: 'Cloud',
    url: 'https://api.githubcopilot.com/mcp/',
    port: '443',
    status: 'Authorization required',
    icon: 'Cable',
  },
];

export const products = [
  {
    name: 'SafeRide',
    label: 'Mobility operations',
    description: 'Connected rider, driver, and customer workflows for safer everyday transport.',
    icon: 'Route',
  },
  {
    name: 'PaletteMath',
    label: 'Decision intelligence',
    description: 'Practical tools that turn operational inputs into clear, defensible decisions.',
    icon: 'ChartNoAxesCombined',
  },
  {
    name: 'Innovation Fleet',
    label: 'Fleet visibility',
    description: 'A unified view of fleet activity, service health, and accountable delivery.',
    icon: 'Truck',
  },
];
